#!/usr/bin/env python
import sys
import datetime

template = """# {date}

## SCRUM Updates

* 

## Todo

## Notes"""

date = (datetime.date.today() if len(sys.argv) < 2
        # Expecting filename in YYYY-MM-DD.foo format
        else sys.argv[1].rsplit(".", 1)[0]).split('/')[-1]
print(template.format(date=date))
