" {{{ vim-plug auto installation
"
set shell=/bin/bash
if empty(glob('~/.config/nvim/autoload/plug.vim'))
  silent !curl -fLo ~/.config/nvim/autoload/plug.vim --create-dirs \
        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
          autocmd VimEnter * PlugInstall
      endif

" }}}
" {{{  Enabled plugins
" set the runtime path to include Vundle and initialize

call plug#begin('~/.vim/bundle')

Plug 'tpope/vim-fugitive'              " git wrapper
Plug 'honza/vim-snippets'              " actual snippets
Plug 'Shougo/deoplete.nvim'             " completion
Plug 'fishbullet/deoplete-ruby'
" Plug 'ervandew/supertab'
" Plug 'SirVer/ultisnips' ", { 'on' : [] }            code snippets
Plug 'tomtom/tcomment_vim'             " easy comments
Plug 'rstacruz/sparkup'                " parser for condensed HTML
" Plug 'vim-airline/vim-airline'         " nice statusline
" Plug 'vim-airline/vim-airline-themes'  " nice statusline - themes
Plug 'jwhitley/vim-matchit'            " better jumping with %
Plug 'vim-scripts/endwise.vim'                     " wisely 'end' functions etc
Plug 'kchmck/vim-coffee-script'        " coffe script support
Plug 'plasticboy/vim-markdown'         " markdown syntax
Plug 'tpope/vim-repeat'                " extend support for repeating with .
Plug 'cohama/lexima.vim'                 " insert mode completion for quotes, etc
Plug 'tpope/vim-surround'              " quickly surround
Plug 'scrooloose/nerdtree' , { 'on': 'NERDTreeToggle' }  " file manager
Plug 'tpope/vim-dispatch'              " start stuff in background
Plug 'nelstrom/vim-textobj-rubyblock'  " text object for selecting ruby blocks
Plug 'kana/vim-textobj-user'           " dependency for vim-textobj-rubyblock
Plug 'christoomey/vim-tmux-navigator'  " seamless navigation between tmux panes and splits
Plug 'tpope/vim-unimpaired'            " set of movement mappings
Plug 'tpope/vim-eunuch.git'            " Chmod, rename, delete etc
Plug 'henrik/vim-qargs'                " adds :Qargs command
Plug 'dhruvasagar/vim-table-mode'      " helps with creating tables
Plug 'benmills/vimux'                  " interact with tmux
Plug 'fmoralesc/vim-pad'               " Evernote replacement
Plug 'gregsexton/gitv'                 " gitk for vim
Plug 'nathanaelkane/vim-indent-guides' " visual indent
Plug 'idanarye/vim-merginal'           " help with merges and rebase
Plug 'junegunn/vim-easy-align'         " easy alignment
Plug 'mattn/gist-vim'                  " create GIST from vim
Plug 'mattn/webapi-vim'                " create GIST from vim
" Plug 'epeli/slimux'                    " start interactive session
" Fuzzy finder
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'
Plug 'rking/ag.vim'                    " vim-ag
Plug 'justinmk/vim-sneak'
Plug 'slim-template/vim-slim'           " slim templating support
Plug 'amiorin/vim-project'
" color packages
Plug 'mhinz/vim-janah'
Plug 'vimoutliner/vimoutliner'          " vim outliner
Plug 'leafgarland/typescript-vim'       " Typescript syntax
Plug 'Shougo/vimproc.vim', {'do' : 'make'} " Dependency for tsuquyomi
Plug 'Quramy/tsuquyomi'                 " typescript completion
Plug 'KabbAmine/vCoolor.vim'            " color picker
Plug 'airblade/vim-gitgutter'
Plug 'hwartig/vim-seeing-is-believing'  "inline ruby
Plug 'kassio/neoterm'
Plug 'janko-m/vim-test'                 "vim-test
Plug 'shime/vim-livedown'
Plug 'vim-scripts/Rename'
Plug 'vimwiki/vimwiki'
Plug 'ClockworkNet/vim-apparmor'
" Plug 'fholgado/minibufexpl.vim'
Plug 'arcticicestudio/nord-vim', { 'branch': 'develop' }
Plug 'andrewstuart/vim-kubernetes'
Plug 'Shougo/neosnippet.vim'
Plug 'Shougo/neosnippet-snippets'
Plug 'w0rp/ale'
Plug 'Glench/Vim-Jinja2-Syntax'
Plug 'thoughtbot/vim-rspec'
"}}}
" {{{ DISABLED Plugs
" Plug 'tpope/vim-rvm'                   " RVM support
" Plug 'mrtazz/simplenote.vim'           " simplenote support
" Plug 'cseelus/vim-colors-clearance'
" Plug 'MaxSt/FlatColor'
" Plug 'blerins/flattown'
" Plug 'rizzatti/dash.vim' - disabled  - took way too long to startup
" Plug 'tpope/vim-bundler' " probably not needed (Jul 2015)
" Plug 'mattly/iterm-colors-pencil'
" Plug 'reedes/vim-colors-pencil'
" Plug 'tpope/vim-rails' "set of rails helpers
" Plug 'skrobul/grb256'          " my version of grb256
" Plug 'vim-scripts/CSApprox'
" Plug 'Lokaltog/vim-easymotion'      " easy motion

" Plug 'git@github.com:Shougo/vimproc.vim.git'
" Plug 'Shougo/unite.vim'             " maybe ctrlp replacement
" Plug 'dbakker/vim-projectroot'      " necessarry to guess project root
" Plug 'Shougo/neomru.vim'            " MRU functionality for Unite.vim
" Plug 'tpope/vim-obsession'          "session management
" Plug 'dhruvasagar/vim-prosession'   "switch between sessions
" Plug 'kien/ctrlp.vim'                  " full path fuzzy finder
" Plug 'jgdavey/vim-turbux'              " Turbo Ruby testing with tmux
" All of your Plugs must be added before the following line

call plug#end()
" }}}
" Autocmd {{{
if has('autocmd')
    filetype plugin indent on
    augroup indentations
        "don't expand tabs if we're in a makefile
        autocmd BufRead,BufNewFile Makefile set ts=4 sw=4 noexpandtab
        "wrap lines in TeX
        autocmd BufRead,BufNewFile *.tex set tw=80
        "wrap lines in .txt files
        autocmd BufNewFile,BufRead *.txt set tw=78
        autocmd BufNewFile,BufRead *.md set tw=78
        " salt states are just yaml files
        autocmd BufNewFile,BufRead *.sls set ft=yaml sw=2 ts=2
        autocmd FileType ruby,eruby set sw=2 ts=2 tw=80
        autocmd FileType coffee set sw=2 ts=2 tw=80
        autocmd FileType python set ts=4 sw=4 et
        autocmd FileType yaml,yml set sw=2 ts=2 tw=80
    augroup END
    augroup completions
        autocmd FileType javascript set omnifunc=javascriptcomplete#CompleteJS
        autocmd FileType html set omnifunc=htmlcomplete#CompleteTags
        autocmd FileType css set omnifunc=csscomplete#CompleteCSS
        autocmd FileType python set omnifunc=pythoncomplete#Complete
        autocmd FileType ruby,eruby set omnifunc=rubycomplete#Complete
    augroup END

    augroup autocorrections
        autocmd!
        " remove trailing whitespaces
        autocmd BufWritePre ruby,eruby,markdown,yaml,yml,javascript,python :%s/\s\+$//e
    augroup END

    augroup markdown
        autocmd!
        autocmd BufNewFile,BufRead *.markdown,*.mdown,*.mkd,*.mkdn,README.md  setf markdown
        autocmd FileType markdown setlocal spell
        autocmd FileType markdown set complete+=k
        autocmd FileType markdown set tw=80 conceallevel=3 wrap
    augroup end

    augroup git
        autocmd!
        " enable spelling on GIT commit messages
        autocmd FileType gitcommit setlocal spell
        " enable auto word wrap in commit messages
        autocmd FileType gitcommit set sw=2 ts=2 tw=80 aw complete+=k
        " enable spelling and autowrap on pull requests
        autocmd VimEnter .git/PULLREQ_EDITMSG nested setlocal filetype=markdown tw=150
        autocmd FileType gitrebase noremap <CR> :Cycle<CR>
    augroup end

    " jump to the last cursor position
    augroup resCur
      autocmd!
      autocmd BufReadPost *
            \ if line("'\"") > 0 && line("'\"") <= line("$") |
            \   exe "normal g`\"" |
            \ endif
    augroup END

    augroup ansible
        autocmd BufRead,BufNewFile */host_vars/* set ft=yaml
        autocmd BufRead,BufNewFile */group_vars/* set ft=yaml
        autocmd BufRead,BufNewFile *.j2 set ft=jinja
    augroup END

    augroup BWCCreateDir
        autocmd!
        autocmd BufWritePre * :call s:MkNonExDir(expand('<afile>'), +expand('<abuf>'))
    augroup END
endif " }}}
" VIM Settings {{{
" syntax highlighting
syntax enable

set bs=2                " Allow backspacing over everything in insert mode
set ai                  " Always set auto-indenting on
set si
"set backup             " Keep a backup file
"set viminfo='20,\"50   " read/write a .viminfo file -- limit to only 50
set history=50          " keep 50 lines of command history
set ts=4                " 4 space wide tabs
set sw=4
set softtabstop=4     "makes backspacing over spaced out tabs work real nice
set expandtab           "expand tabs to spaces
set ignorecase
set background=dark     "awesome for terminals with crappy colors (putty!)
set tagstack            "lets you push and pop your jumps with ctrl+]
set pastetoggle=<F11>   "when you're pasting stuff this keeps it from getting
                        "all whacked out with indentation
set noshowmatch
set showmode
set smarttab
set nrformats-=octal
set ttimeout
set ttimeoutlen=100
set incsearch
set spellfile=~/dotfiles/vim/spell/en.utf-8.add
set modelines=5         " check for vim settings in X lines of read file
set complete-=k         " autocompletion - disable dictionary based
set hlsearch
set ignorecase
set smartcase
set hidden " do not save history when leaving buffer
set foldlevelstart=1
set formatoptions=tcrqnj
set diffopt=filler
" set lazyredraw
set number
" In many terminal emulators the mouse works just fine, thus enable it.
if has('mouse')
  set mouse=a
endif
" set cursorline

" explorer
let g:explVertical=1      " Split vertically
let g:explSplitRight=1    " Put new window to the right of the explorer

""""""""""""""""""""""""""""""
" => Statusline
""""""""""""""""""""""""""""""
" Always hide the statusline
set laststatus=1
set ruler               " Show the cursor position all the time
set rulerformat=%30(%<%m%y%h%r%=%l,%c\ %P%)
set showcmd
set wildmode=longest,list,full
set wildmenu

set autoread " reads the file when it has been changed outside vim
" set encoding=utf-8

" files related
set nobackup
set nowritebackup
set noswapfile
set fileformats=unix,dos,mac

" Searching in the menu
set completeopt=menuone,longest,preview

set clipboard=unnamed
" Make 81st column stand out
highlight ColorColumn ctermbg=Brown ctermfg=Black
call matchadd('ColorColumn', '\%81v', 100)

" let &colorcolumn=join(range(81,999),",")

"====[ Make tabs, trailing whitespace, and non-breaking spaces visible ]======
"exec "set listchars=tab:\uBB\uBB,trail:•,nbsp:~"
set listchars=tab:→\ ,eol:↲,nbsp:␣,trail:•,extends:⟩,precedes:⟨

highlight SpecialKey ctermbg=none " make the highlighting of tabs less annoying
set nolist
set showbreak=↪


" move focus to correct place after the split
set splitbelow " open splits below current pane
set splitright " ... to the right of current pane
let $NVIM_TUI_ENABLE_CURSOR_SHAPE=0

" }}}
" normal mode mappings (general) {{{
nnoremap <silent> <Leader>q :nohlsearch<CR><C-L>
nnoremap <CR> :noh<CR><CR>

" Replace all occurences of word under cursor
nnoremap <Leader>z :%s/\<<C-r><C-w>\>//g<Left><Left>
" space bar folding
nnoremap  <silent>  <space> :exe 'silent! normal! za'.(foldlevel('.')?'':'l')<cr>

" Buffers - explore/next/previous: Alt-F12, F12, Shift-F12.
nnoremap <F12> :bn<CR>
nnoremap <S-F12> :bp<CR>

" disable arrows
noremap <Up> <Nop>
noremap <Down> <Nop>
noremap <Left> <Nop>
noremap <Right> <Nop>

" Don't use Ex mode, use Q for formatting
map Q gq

" Smart way to move btw. windows
" map <C-j> <C-W>j
" map <C-k> <C-W>k
" map <C-h> <C-W>h
" map <C-l> <C-W>l

" lookup in Dash
nmap <silent> <leader>d <Plug>DashSearch

" buffer navigation
" new buffer (empty)
nmap <silent> <leader>bt :enew<CR>
" next buffer
nmap <silent> <leader>n :bnext<CR>
" previous buffer
nmap <silent> <leader>p :bprevious<CR>
"close the buffer and replace with previous
nmap <silent> <leader>bc :bp <BAR> bd #<CR>
"close the buffer
nmap <silent> <leader>bd :bd<CR>
" show all open buffers in buffer explorer
" nmap <silent> <leader>b :ls<CR>
" nmap <silent> <leader>b :CtrlPBuffer<cr>
map <Leader>bl :Buffers<CR>
vmap <Leader>bl :Buffers<CR>

map ' :Buffers<CR>
vmap ' :Buffers<CR>
" ruby context endings - insert marks
nmap <Leader>z /end%y$%A # p:nohlsearch

" Map `kj` to ESC
imap kj <ESC>

" automatically insert a \v before any search string, so search uses normal regexes
nnoremap / /\v
vnoremap / /\v

" Use Q for formatting the current paragraph (or selection)
vmap Q gq
nmap Q gqap

" Easy reloading of vimrc
map <silent> <leader>V :source ~/.vimrc<CR>:filetype detect<CR>:exe ":echo 'vimrc reloaded'"<CR>

" Switch to alternative file quickly
" nnoremap <Tab><Tab> <C-^>

if has("nvim")
    " neovim's terminal
    tnoremap <C-h> <C-\><C-n><C-w>h
    tnoremap <C-j> <C-\><C-n><C-w>j
    tnoremap <C-k> <C-\><C-n><C-w>k
    tnoremap <C-l> <C-\><C-n><C-w>l
    nnoremap <A-h> <C-w>h
    nnoremap <A-j> <C-w>j
    nnoremap <A-k> <C-w>k
    nnoremap <A-l> <C-w>l
endif


" autocmd BufEnter term://* startinsert

" }}}
" visual mode mappings {{{

" indent / deindent after selecting the text with (⇧ v), (.) to repeat.
vnoremap <Tab> >
vnoremap <S-Tab> <
" comment / decomment & normal comment behavior
vmap <C-m> gc
" Text wrap simpler, then type the open tag or ',"
vmap <C-w> S
" Cut, Paste, Copy
vmap <C-x> d
vmap <C-v> p
vmap <C-c> y

" "}}}
" gui related stuff {{{
if has("gui_running")
   let s:uname = system("uname")
   if s:uname == "Darwin\n"
      set guifont=Sauce\ Code\ Powerline:h14
      set guioptions-=r
   endif
endif
" }}}
" Plugins config {{{
" CtrlP {{{
" let g:ctrlp_custom_ignore = '\v[\/]\.(git|hg|svn)$'
set wildignore+=**/node_modules
" let g:ctrlp_open_new_file = "r"
" let g:ctrlp_match_func = {'match' : 'matcher#cmatch' } "fuzzy matching with ctrlp+cmatcher"
let g:ctrlp_extensions = ['tag']
" let g:ctrlp_cmd = 'CtrlPMixed'
nmap <C-S-p> :CtrlPMixed<CR>
" }}}
" Completion plugins (YCM/UltiSnip/Supertab) {{{
" Ultisnip - disabled shortcuts so they don't conflict with YouCompleteMe
" let g:SuperTabDefaultCompletionType = '<C-x><C-o>'
" better key bindings for UltiSnipsExpandTrigger
" let g:UltiSnipsExpandTrigger = "<tab>"
" let g:UltiSnipsJumpForwardTrigger = "<tab>"
" let g:UltiSnipsJumpBackwardTrigger = "<s-tab>"
"}}}
" vim-airline {{{
let g:airline_theme = 'nord'
let g:airline_powerline_fonts = 0
let g:airline_left_sep = ''
let g:airline_right_sep = ''
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#fnamemod = ':t' "display just filenames
let g:airline#extensions#tabline#buffer_nr_show = 1
if !exists('g:airline_symbols')
  let g:airline_symbols = {}
endif
let g:airline_symbols.branch = ''
" disable file format and encoding
" let g:airline_section_y = ''
" display
let g:airline_section_z = '%l,%c'
" }}}
" {{{ vim-markdown - no folding
" let g:vim_markdown_folding_disabled=0
let g:vim_markdown_folding_disabled = 0
let g:vim_markdown_new_list_item_indent = 2
" }}}
" NERDTree - autoclose when last buffer {{{
map <F4> :NERDTreeToggle<CR>
" }}}
" instant markdown {{{
let g:instant_markdown_slow = 1
" "}}}
" tcomment {{{
let g:tcomment#replacements_xml={}
" }}}
" fugitive {{{
nnoremap <Leader>ga :Git add %:p<CR><CR>
nnoremap <Leader>gs :Gstatus<CR>
nnoremap <Leader>gc :Gcommit -v -q<CR>
nnoremap <Leader>gt :Gcommit -v -q %:p<CR>
nnoremap <Leader>gd :Gdiff<CR>
nnoremap <Leader>ge :Gedit<CR>
nnoremap <Leader>gr :Gread<CR>
nnoremap <Leader>gw :Gwrite<CR><CR>
nnoremap <Leader>gl :silent! Glog<CR>:bot copen<CR>
nnoremap <Leader>gp :Ggrep<Space>
nnoremap <Leader>gm :Gmove<Space>
nnoremap <Leader>gb :Git branch<Space>
nnoremap <Leader>go :Git checkout<Space>
nnoremap <Leader>gps :Gpush<CR>
nnoremap <Leader>gpl :Gpull<CR>
" git merges
map <silent> <leader>2 :diffget LOCAL<CR> :diffupdate<CR>
map <silent> <leader>3 :diffget REMOTE<CR> :diffupdate<CR>
" gitv
nnoremap <Leader>gv :Gitv --all<CR>
nnoremap <Leader>gV :Gitv! --all<CR>
vmap <leader>gV :Gitv! --all<cr>

" }}}
" Geeknote markdown by default {{{2
let g:GeeknoteFormat="markdown"
"}}}
" {{{2 prosession configuration
let g:prosession_dir = '~/.vim/session/'
let g:prosession_tmux_title = 1
"}}}
" vim-pad {{{2
let g:pad#dir = '~/Dropbox/notes'
let g:pad#maps#new = "<meta>n"
let g:pad#search_backend = 'ag'
let g:pad#default_format = "votl"
let g:pad#default_file_extension = '.otl'
"let g:pad#window_height = 25
let g:pad#open_in_split = 0   " open in main window

let g:pad#title_first_line = 1
" disable default mappings

let g:pad#set_mappings = 0
nmap <silent> <F1> <Plug>(pad-list)
nmap <silent> <F2> <Plug>(pad-new)
nmap ,pl <Plug>(pad-list)
nmap ,pn <Plug>(pad-new)
nmap ,ps <Plug>(pad-incremental-new-note)

" bug workaround
" see https://github.com/fmoralesc/vim-pad/issues/75#issuecomment-257467586

" switching between markdown and otl
function! PadMarkdown()
    set ft=markdown
    call Rename(expand("%:r") . ".md", '')
    let g:pad#default_format = "markdown"
    let g:pad#default_file_extension = '.md'
endfunction
command! -bar PadMarkdown call PadMarkdown()

function! PadOTL()
    set ft=votl
    call Rename(expand("%:r") . ".votl", '')
    let g:pad#default_format = "votl"
    let g:pad#default_file_extension = '.otl'
endfunction
command! -bar PadOTL call PadMarkdown()
"}}}
" easy align{{{2
"
" Start interactive EasyAlign in visual mode (e.g. vipga)
xmap ga <Plug>(EasyAlign)
"
" Start interactive EasyAlign for a motion/text object (e.g. gaip)
nmap ga <Plug>(EasyAlign)
""}}}
" vim-gist {{{2
let g:gist_api_url = 'https://github.rackspace.com/api/v3'
let g:gist_post_private = 1
let g:gist_show_privates = 1
""}}}
" deoplete {{{{
let g:deoplete#enable_at_startup = 1
let g:deoplete#file#enable_buffer_path = 1
let g:deoplete#max_list = 15
" tab completion
" inoremap <Leader><Tab> <Tab>
inoremap <silent><expr> <Tab> pumvisible() ? "\<C-n>" : deoplete#mappings#manual_complete()
autocmd InsertLeave,CompleteDone * if pumvisible() == 0 | pclose | endif
" }}}}
" vim-ruby {{{
let g:ruby_indent_block_style = 'do'
" }}}
" ag - The Silver Searcher {{{
if executable('ag')
  " Use ag over grep
  set grepprg=ag\ --nogroup\ --nocolor

  " Use ag in CtrlP for listing files. Lightning fast and respects .gitignore
  let g:ctrlp_user_command = 'ag %s -l --nocolor -g ""'

  " ag is fast enough that CtrlP doesn't need to cache
  let g:ctrlp_use_caching = 0
endif
" let g:ag_prg="/usr/local/bin/ag --vimgrep"

" }}}
" slimux - interactive sessions started directly from vim {{{
map <Leader>l :SlimuxREPLSendLine<CR>
vmap <Leader>l :SlimuxREPLSendSelection<CR>

" }}}
" fzf - fuzzy search {{{
map <C-p> :FZF<CR>
vmap <C-p> :FZF<CR>
" https://github.com/junegunn/fzf.vim/issues/83#issuecomment-205886405
"let g:fzf_command_prefix = 'Fzf'

" }}}
" projects {{{
let g:project_use_nerdtree = 1
set rtp+=~/.vim/bundle/vim-project/
call project#rc("~/devel")
Project 'scratch'
Project '~/dotfiles'
Project 'unipede'
Project 'config-gen'
Project 'salt-secrets'
Project 'salt-marek'
Project 'salt'
Project 'bbauth'
" }}}
" vim-outliner {{{
" autocmd! FileType votl inoremap <C-n> <ESC>:call UltiSnips#ExpandSnippet()<CR>i
autocmd! FileType votl inoremap <C-n> <Esc>:call UltiSnips#ExpandSnippetOrJump()<CR>
autocmd! FileType votl set nolist foldlevel=1

" }}}
" tsuquyomi {{{
" disable neomake makers for typescript to avoid duplication
let g:neomake_typescript_enabled_makers = []
let g:tsuquyomi_disable_default_mappings = 1
" }}}
" tmux-navigate {{{
" temp fix for https://github.com/neovim/neovim/issues/2048
if has('nvim')
    nmap <silent> <BS> :TmuxNavigateLeft<CR>
endif
" }}}
" {{{ tableize / table mode
let g:table_mode_map_prefix = "<leader>y"
let g:table_mode_corner='|' "markdown tables"

" }}}
" {{{ seeing is believing
" Enable seeing-is-believing mappings only for Ruby
augroup seeingIsBelievingSettings
  autocmd!

  autocmd FileType ruby nmap <buffer> <M-Enter> <Plug>(seeing-is-believing-mark-and-run)
  autocmd FileType ruby xmap <buffer> <M-Enter> <Plug>(seeing-is-believing-mark-and-run)

  autocmd FileType ruby nmap <buffer> <F5> <Plug>(seeing-is-believing-mark)
  autocmd FileType ruby xmap <buffer> <F5> <Plug>(seeing-is-believing-mark)
  autocmd FileType ruby imap <buffer> <F5> <Plug>(seeing-is-believing-mark)

  autocmd FileType ruby nmap <buffer> <F6> <Plug>(seeing-is-believing-run)
  autocmd FileType ruby imap <buffer> <F6> <Plug>(seeing-is-believing-run)
augroup END
" }}}
" {{{ vim-test
nnoremap <silent> ,rt :TestSuite<cr>
nnoremap <silent> ,rf :TestFile<cr>
nnoremap <silent> ,rn :TestNearest<cr>
nnoremap <silent> ,rr :TestLast<cr>
nnoremap <silent> ,rv :TestVisit<cr>
" Useful maps
" hide/close terminal
nnoremap <silent> ,th :call neoterm#close()<cr>
" clear terminal
nnoremap <silent> ,tl :call neoterm#clear()<cr>
" kills the current job (send a <c-c>)
nnoremap <silent> ,tc :call neoterm#kill()<cr>
let test#strategy = "dispatch"
" }}}
" vim-livedown {{{
" should markdown preview get shown automatically upon opening markdown buffer
let g:livedown_autorun = 0

" should the browser window pop-up upon previewing
let g:livedown_open = 1

" the port on which Livedown server will run
let g:livedown_port = 1337

nmap gm :LivedownToggle<CR>
" }}}
" {{{ vimwiki
let g:vimwiki_list = [{'path': '~/Dropbox/notes/wiki/',
            \ 'syntax': 'markdown', 'ext': '.md'}]

let g:vimwiki_table_mappings = 0
let g:vimwiki_table_auto_fmt = 0


" }}}
" neosnippet {{{
"
" SuperTab like snippets' behavior.
" Note: It must be "imap" and "smap".  It uses <Plug> mappings.
imap <expr><TAB>
    \ pumvisible() ? "\<C-n>" :
    \ neosnippet#expandable_or_jumpable() ?
    \    "\<Plug>(neosnippet_expand_or_jump)" : "\<TAB>"
smap <expr><TAB> neosnippet#expandable_or_jumpable() ?
      \ "\<Plug>(neosnippet_expand_or_jump)" : "\<TAB>"
" Enable snipMate compatibility feature.
let g:neosnippet#enable_snipmate_compatibility = 1

" let g:neosnippet#snippets_directory="~/.vim/UltiSnips,~/.vim/bundle/vim-kubernetes/UltiSnips"
let g:neosnippet#snippets_directory="~/dotfiles/snippets/"

	" Expand the completed snippet trigger by <CR>.
imap <expr><CR>
  \ (pumvisible() && neosnippet#expandable()) ?
  \ "\<Plug>(neosnippet_expand)" : "\<CR>"
"}}}
" {{{ vim-rspec
map <Leader>t :call RunCurrentSpecFile()<CR>
map <Leader>s :call RunNearestSpec()<CR>
map <Leader>rl :call RunLastSpec()<CR>
map <Leader>ra :call RunAllSpecs()<CR>
let g:rspec_command = "Dispatch -compiler=rspec bundle exec rspec {spec} --format=progress"
" Yoinked from rails.vim to support rspec keyword highlighting outside Rails
" project folders
autocmd BufRead *_spec.rb syn keyword rubyRspec describe context it its specify shared_context shared_examples shared_examples_for shared_context include_examples include_context it_should_behave_like it_behaves_like before after around subject scenario feature background given described_class violated pending expect expect_any_instance_of allow allow_any_instance_of double instance_double mock xit fit
highlight def link rubyRspec Function
" }}}
" end of plugin config }}}
"{{{ colorscheme
if has('termguicolors')
    set termguicolors
endif
let g:nord_italic_comments = 0
colorscheme nord

" local modifications
" search results blue instead of orange
hi Search ctermfg=234 ctermbg=221 guifg=#101112 guibg=#B7C0C9
" more distinct line nr
hi LineNr ctermfg=237 guibg=#2F3339 guifg=#707885

" fix gitgutter background
hi GitGutterAdd ctermfg=2 guifg=#009900 guibg=#2F3339
hi GitGutterDelete ctermfg=1 guifg=#ff2222 guibg=#2F3339
hi GitGutterChange ctermfg=3 guifg=#bbbb00 guibg=#2F3339

" color constants with blue instead of orange
hi Type ctermfg=173 guifg=#23A1D3
"}}}
" custom commands {{{
" bind \a (backward slash) to grep shortcut
"command! -nargs=+ -complete=file -bar Ag silent! grep! <args>|cwindow|redraw!
" map ag to leader a
nnoremap <Leader>a :Ag<SPACE>
function! ArrayConvertToW()
    execute "normal /=\s+<cr>evf]"
    s/\%V,/ /ge
    s/\v\[(.*)\]/%w(\1)/
 endfunction
 command! ArrayConvertToW :call ArrayConvertToW()<cr>
" json prettyfiy
command! JSONPretty %!python -m json.tool
" ruby - convert hashes to 1.9+ syntax
command! NewRubyHashes :%s/:\([^ ]*\)\(\s*\)=>/\1:/g
" retab to n spaces
command! -nargs=1 -range SuperRetab <line1>,<line2>s/\v%(^ *)@<= {<args>}/\t/g
" load all feature branch commits into buffer
command! PRlog Glog master..HEAD --reverse --

" create file with subdirectories if needed :E
function! s:MKDir(...)
    if         !a:0
           \|| stridx('`+', a:1[0])!=-1
           \|| a:1=~#'\v\\@<![ *?[%#]'
           \|| isdirectory(a:1)
           \|| filereadable(a:1)
           \|| isdirectory(fnamemodify(a:1, ':p:h'))
        return
    endif
    return mkdir(fnamemodify(a:1, ':p:h'), 'p')
endfunction
command! -bang -bar -nargs=? -complete=file E :call s:MKDir(<f-args>) | e<bang> <args>

function! s:MkNonExDir(file, buf)
    if empty(getbufvar(a:buf, '&buftype')) && a:file!~#'\v^\w+\:\/'
        let dir=fnamemodify(a:file, ':h')
        if !isdirectory(dir)
            call mkdir(dir, 'p')
        endif
    endif
endfunction
" Useful trick when I've forgotten to `sudo' before editing a file:
cmap w!! w !sudo tee % >/dev/null


" }}}
" local machine config {{{
if filereadable(expand("~/.vimrc.local"))
  source ~/.vimrc.local
endif
"}}}
" colorscheme overrides {{{
hi MatchParen     ctermfg=0 ctermbg=6 guifg=#EBCB8B guibg=#88C0D0
"}}}
" vim: foldmethod=marker foldlevel=0
